swagger: '2.0'
info:
  title: Dinner Solutions API
  description: An API for Dinner Solutions, focused on mobile
  version: "0.1.0"
host: api.davidjfelix.com
schemes:
  - https
basePath: /v0
produces:
  - application/json
paths:
  /user/{user_id}:
    get:
      summary: User by id
      description: |
        The user endpoint returns information about a given user or a set of users.
      parameters:
        - name: user_id
          in: path
          description: The id of the user
          required: true
          type: string
          format: uuid
      tags:
        - users
      responses:
        200:
          description: A user object.
          schema:
            type: object
  /me:
    get:
      summary: Me
      description: |
        The me endpoint returns information about my user profile.
      tags:
        - users
      responses:
        200:
          description: A user object.
          schema:
            type: object
  /me/by-token:
    post:
      summary: Me by token
      description: |
        The me by token endpoint returns information about my user profile.
        It takes a token to authenticate.
      tags:
        - users
      responses:
        200:
          description: A user object.
          schema:
            type: object
  /meals/{meal_id}:
    delete:
      summary: Delete a meal
      description: |
        Delete a meal.
      parameters:
        - name: meal_id
          in: path
          description: The id of the meal
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: OK
          schema:
            type: object
    get:
      summary: Get a meal
      description: |
        Get a meal
      parameters:
        - name: meal_id
          in: path
          description: The id of the meal
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: OK
    patch:
      summary: Partially update a meal
      description: |
        Partially update a meal
      parameters:
        - name: meal_id
          in: path
          description: The id of the meal
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: OK
    post:
      summary: Post a meal
      description: |
        Post a meal
      parameters:
        - name: meal_id
          in: path
          description: The id of the meal
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: OK
    put:
      summary: Update a meal
      description: |
        Update a meal
      parameters:
        - name: meal_id
          in: path
          description: The id of the meal
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: OK
