swagger: '2.0'
info:
  title: Dinner Solutions API
  description: An API for Dinner Solutions, focused on mobile
  version: "0.1.0"
host: api.davidjfelix.com
schemes:
  - https
basePath: /v0
produces:
  - application/json
