swagger: '2.0'
info:
  title: Dinner Solutions API
  description: An API for Dinner Solutions, focused on mobile
  version: "0.1.0"
host: api.davidjfelix.com
schemes:
  - http
  - https
basePath: /v0
produces:
  - application/json
paths:
  /address:
    get:
      summary: a
      description: a
      tags:
        - addresses
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Address"
    post:
      summary: a 
      description: a
      tags:
        - addresses
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Address"
  /address/{address_id}:
    delete:
      summary: a
      description: a
      tags:
        - addresses
      parameters:
        - name: address_id
          in: path
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: OK
    get:
      summary: a
      description: a
      tags:
        - addresses
      parameters:
        - name: address_id
          in: path
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: OK
    patch:
      summary: a
      description: a
      tags:
        - addresses
      parameters:
        - name: address_id
          in: path
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: OK
    put:
      summary: a
      description: a
      tags:
        - addresses
      parameters:
        - name: address_id
          in: path
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: OK
  /auth/google/by-jwt:
    post:
      summary: Accepts JWT from google.
      description: |
        Accepts JWT from google.
      consumes:
        - text/plain
      parameters:
        - name: jwt
          in: body
          required: true
          description: |
            A signed Google JWT
          schema:
            $ref: '#/definitions/JWT'
      tags:
        - auth
      responses:
        200:
          description: Authentication Accepted
          schema:
            $ref: '#/definitions/BearerToken'
        400:
          description: Malformed Request. Your request wasn't correct.
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Unauthorized. Your authentication failed.
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Forbidden. Your authentication succeeded but you are not authorized.
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Upstream Server Error.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected Error
          schema:
            $ref: '#/definitions/Error'
  /users:
    post:
      summary: Create new user 
      description: Create new user
      tags:
        - users
      responses:
        200:
          description: OK
    
  /users/{user_id}:
    get:
      summary: User by id
      description: |
        The user endpoint returns information about a given user or a set of users.
      parameters:
        - name: user_id
          in: path
          description: The id of the user
          required: true
          type: string
          format: uuid
      tags:
        - users
      responses:
        200:
          description: A user object.
          schema:
            $ref: '#/definitions/User'
        404:
          description: User is not found
          schema:
            $ref: '#/definitions/Error'
  /me:
    get:
      summary: Me
      description: |
        The me endpoint returns information about my user profile.
      tags:
        - users
      responses:
        200:
          description: A user object.
          schema:
            $ref: '#/definitions/User'
  /me/by-token:
    post:
      summary: Me by token
      description: |
        The me by token endpoint returns information about my user profile.
        It takes a token to authenticate.
      consumes:
        - text/plain
      parameters:
        - name: jwt
          required: true
          in: body
          schema:
            $ref: "#/definitions/JWT"
      tags:
        - users
      responses:
        200:
          description: A user object.
          schema:
            $ref: "#/definitions/UserAndBearer"
  /meals:
    get:
      summary: Get a meals collection.
      description: |
        The meals get collection endpoint allows clients to search for meals by parameters.
        It returns meals based on relevance to the search parameters.
      parameters:
        - name: lat
          in: query
          description: The geographic latitude of the search.
          required: false
          type: number
          format: double
        - name: lng
          in: query
          description: The geographic longitude of the search.
          required: false
          type: number
          format: double
      tags:
        - meals
        - search
      responses:
        200:
          description: The search parameters yielded a result set.
          schema:
            $ref: '#/definitions/MealCollection'
    post:
      summary: Post a new meal.
      description: |
        The meals post endpoint allows clients to create a new meal.
      parameters:
        - name: meal
          in: body
          schema:
            $ref: '#/definitions/NewMeal'
      tags:
        - meals
      responses:
        201:
          description: The meal posted correctly
          schema:
            $ref: '#/definitions/Meal'
  /meals/{meal_id}:
    delete:
      summary: Delete a meal by id
      description: |
        The delete action marks the meal as inactive.
      tags:
        - meals
      parameters:
        - name: meal_id
          in: path
          description: The id of the meal
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Meal'
    get:
      summary: Get a meal
      description: |
        Get a meal
      tags:
        - meals
      parameters:
        - name: meal_id
          in: path
          description: The id of the meal
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Meal'
    patch:
      summary: Partially update a meal
      description: |
        Partially update a meal
      tags:
        - meals
      parameters:
        - name: meal_id
          in: path
          description: The id of the meal
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Meal'
    put:
      summary: Update a meal
      description: |
        Update a meal
      tags:
        - meals
      parameters:
        - name: meal_id
          in: path
          description: The id of the meal
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Meal'
  /ingredients:
    get:
      summary: Get a list of ingredients
      description: |
        Get a list of ingredients
      tags:
        - search
        - ingredients
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/IngredientCollection"
        default:
          description: Unexpected Server Error
          schema:
            $ref: "#/definitions/Error"
definitions:
  Address:
    type: object
  BearerToken:
    type: object
    required:
      - type
      - data
    properties:
      type:
        type: string
      data:
        type: string
  User:
    type: object
    required:
      - user_id
      - name
      - email
    properties:
      user_id:
        $ref: "#/definitions/UUID"
      name:
        type: string
      email:
        type: string
        format: email
  UserAndBearer:
    type: object
    required:
      - token
      - user
    properties:
      token:
        $ref: "#/definitions/BearerToken"
      user:
        $ref: "#/definitions/User"
  Meal:
    type: object
    required:
      - meal_id
      - name
      - description
      - ingredients
      - location
      - availableFrom
      - availableTo
      - isActive
      - portions
      - portionsAvailable
      - price
      - lastUpdated
      - metadata
      - allergens
    properties:
      meal_id:
        $ref: "#/definitions/UUID"
      name:
        type: string
      description:
        type: string
      ingredients:
        type: array
        items:
          $ref: "#/definitions/Ingredient"
      location:
        $ref: "#/definitions/Location"
      availableFrom:
        $ref: "#/definitions/Time"
      availableTo:
        $ref: "#/definitions/Time"
      lastUpdated:
        $ref: "#/definitions/Time"
      isActive:
        type: boolean
      portions:
        type: integer
      portionsAvailable:
        type: integer
      price:
        type: number
        format: double
      metadata:
        type: array
        items:
          $ref: "#/definitions/MealMetaData"
      allergens:
        type: array
        items:
          $ref: "#/definitions/Allergen"
  MealCollection:
    type: object
    required:
      - meals
    properties:
      meals:
        type: array
        items:
          $ref: '#/definitions/Meal'
  NewMeal:
    type: object
    required:
      - name
      - description
      - ingredients
      - location
      - availableFrom
      - availableTo
      - portions
      - price
      - metadata
      - allergens
    properties:
      name: 
        type: string
      description:
        type: string
      portions:
        type: integer
      metadata:
        type: array
        items:
          $ref: "#/definitions/MealMetaData"
      allergens:
        type: array
        items: 
          $ref: "#/definitions/Allergen"
      price: 
        type: number
        format: double
      ingredients:
        type: array
        items:
          $ref: "#/definitions/Ingredient"
      location:
        $ref: "#/definitions/Location"
      availableFrom:
        $ref: "#/definitions/Time"
      availableTo:
        $ref: "#/definitions/Time"
  Location:
    type: object
    format: GeoJSON
    required:
      - type
      - coordinates
    properties:
      type:
        type: string
        format: GeoJSON Type
      coordinates:
        type: array
        items:
          $ref: "#/definitions/Coordinate"
  UUID:
    type: string
    format: UUID v4
    description: |
      A Universally Unique Identifier.
      A 128-bit randomly generated ID, in hexidecimal, UUID notation.
      Randomly generated using the UUID version 4 specification.
  Coordinate:
    type: number
    format: Coordinate
  JWT:
    type: string
    format: encoded JWT
    description: |
      A UTF-8 encoded string of base64 encoded JSON objects, seperated by periods.
      The format is "Header.Payload.Signature".
  Time:
    type: string
    format: RFC3339
    description: |
      An RFC3339 datetime as a string.
  MealMetaData:
    type: string
  Ingredient:
    type: object
    required:
      - name
      - description
    properties:
      name:
        type: string
      description:
        type: string
  Allergen:
    type: object
    properties:
      allergen_id:
        $ref: "#/definitions/UUID"
      name:
        type: string
      description:
        type: string
  IngredientCollection:
    type: object
    required:
      - ingredients
    properties:
      ingredients:
        type: array
        items:
          $ref: "#/definitions/Ingredient"
  Error:
    type: object
    required:
      - error
      - details
    properties:
      error:
        type: integer
      details:
        type: string
