swagger: '2.0'
info:
  title: Dinner Solutions API
  description: An API for Dinner Solutions, focused on mobile
  version: "0.1.0"
host: api.davidjfelix.com
schemes:
  - https
basePath: /v0
produces:
  - application/json
paths:
  /user/{user_id}:
    get:
      summary: Product Types
      description: |
        The user endpoint returns information about a given user or a set of users.
      parameters:
        - name: user_id
          in: path
          description: The id of the user
          required: true
          type: string
          format: uuid
      tags:
        - users
      responses:
        200:
          description: An array of products
          schema:
            type: object
  
